/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.16.0_@tiptap+core@3.16.0_@tiptap+pm@3.16.0__@tiptap_f252403f263e09a779de5814cdd5fd34/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.16.0_@tiptap+core@3.16.0_@tiptap+pm@3.16.0__@tiptap_f252403f263e09a779de5814cdd5fd34/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  }
}
